openapi: 3.0.3

servers:
  - url: http://localhost:8000 # put your localhost server url here
    description: localhost

info:
  description: Short description about the project
  version: "1.0.0"
  title: example-project

paths:
  # define your paths here
